- name: Add or Remove ESXi host and Release the Maintenance Mode
  hosts: all
#  gather_facts: no
  tasks:
    - name: Add or Remove ESXi host to/from vCenterServer
      vmware_host:
        validate_certs: False
        datacenter_name: DC
        cluster_name: CL
#        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
#        username: "{{lookup('env', 'VMWARE_USER')}}"
#        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        esxi_hostname: "{{esxi_host}}"
        esxi_username: "{{esxi_user}}"
        esxi_password: "{{esxi_pass}}"
        state: present
      delegate_to: localhost
#    - name: Manage Maintenance Mode
#      local_action:
#        module: vmware_maintenancemode
#        validate_certs: False
#        esxi_hostname: "{{esxi_host}}"
#        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
#        username: "{{lookup('env', 'VMWARE_USER')}}"
#        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
#        state: absent
#      when: esxi_state == "present"
