---
- name: ESXi vSwitch Information
  hosts: all
  gather_facts: no
  tasks:
    - name: Show vss facts
      vmware_vswitch_info:
        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
        username: "{{lookup('env', 'VMWARE_USER')}}"
        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        validate_certs: False
        esxi_hostname: "{{ esxi_host }}"
      delegate_to: localhost
      register: vss_facts
    - debug:
        var: vss_facts
