---
- name: Get VM Tag & httpd install & Firewall (80/443) config
  hosts: all
  gather_facts: yes
  tasks:
    - name: Confirm VM Tag & Register to variable
      vmware_guest_info:
        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
        username: "{{lookup('env', 'VMWARE_USER')}}"
        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        validate_certs: False
        datacenter: DC
        name: "{{ansible_nodename}}"
        tags: yes
      register: vm_facts
      delegate_to: localhost

    - name: httpd install
      yum:
        name: httpd
        state: latest
      when: vm_facts.instance.tags == ["New_VM"]

    - name: httpd running & Enabled
      service:
        name: httpd
        state: started
        enabled: yes
      when: vm_facts.instance.tags == ["New_VM"]

    - name: Firewall Setting 80/443
      firewalld:
        service: "{{item}}"
        zone: public
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - http
        - https
      when: vm_facts.instance.tags == ["New_VM"]
