---
- name: Move Object between AACs
  hosts: all
  gather_facts: no
  tasks:
    - name: Export AAC Object
      ansible.controller.export:
#        controller_host: "{{lookup('env', 'CONTROLLER_HOST')}}"
#        controller_username: "{{lookup('env', 'CONTROLLER_USERNAME')}}"
#        controller_password: "{{lookup('env', 'CONTROLLER_PASSWORD')}}"
        controller_host: "student1.7w6qg.example.opentlc.com"
        controller_username: "admin"
        controller_password: "25o4n68m"
        validate_certs: false
        inventory: 'all'
      register: export_output
      
    - name: Inport AAC Object
      ansible.controller.import:
#        controller_host: "{{lookup('env', 'CONTROLLER_HOST')}}"
#        controller_username: "{{lookup('env', 'CONTROLLER_USERNAME')}}"
#        controller_password: "{{lookup('env', 'CONTROLLER_PASSWORD')}}"
        controller_host: "student2.7w6qg.example.opentlc.com"
        controller_username: "admin"
        controller_password: "25o4n68m"
        validate_certs: false
        assets: "{{ export_output.assets }}"
